Introducing a star (direct source) for clear sky simulations
atmtools/arts pull request #385
Opened 2021-11-16 09:43 UTC by m-brath

2022-08-02 10:37 UTC, olemke commented
Anything left to do before merging this PR?

2022-08-03 09:26 UTC, riclarsson requested changes
Some small comments

2022-08-03 10:07 UTC, olemke commented on src/m_gas_scattering.cc
> +  gas_scattering_agenda = Agenda();
Fixed

2022-08-05 09:24 UTC, riclarsson commented on src/m_refraction.cc
> +void refr_index_waterVisibleNIR(GriddedField3& complex_refr_index,
Should probably be named complex_refr_indexWaterVisibleNIR

Add real value limit to documentation in methods.cc

2022-08-05 09:26 UTC, riclarsson commented on src/m_refraction.cc
> +void complex_refr_indexTConstant(GriddedField3& complex_refr_index,
The temperature seems to not be used locally by this function so it should probably be dropped from the name

2022-08-05 09:52 UTC, riclarsson commented on src/workspace.cc
> +      NAME("in_los"),
Perhaps name these two as gas_scattering_los_in and gas_scattering_los_out

2022-08-05 09:54 UTC, riclarsson commented on src/workspace.cc
> +          "Incoming line-of-sight.\n"
Copy pasta?

The physical use should probably be in the variable description

2022-08-08 10:02 UTC, riclarsson approved these changes
I think this can be merged now.  Great work :)

2022-08-08 11:43 UTC, merged