Add CIA example routine
atmtools/arts pull request #594
Opened 2023-01-25 16:36 UTC by riclarsson

Same as for LBL but using CIA routines.

I still requires two reviewers to look at this before I will merge.

This code also found and fixed an error in the reading-routine that is now fixed.  Since no one ran into this problem before I think it is not urgent so I will not split this PR.

@stefanbuehler , the example shows O2-CIA-O2-0, which is far into the THz range, so I think that it represents well the idea you mentioned before --- I did extend ARTS CIA to higher frequencies by porting newer HITRAN code.

To @erikssonpatrick , @olemke and @stefanbuehler , I think CIA is poorly implemented in ARTS.  I do not see the need for the final index, separating the internal data structure.  The example I give for how to deal with adding all O2-CIA-O2 absorption is the only way to do this today.

I also still think that the example for adding additional `abs_species` just to get at a VMR that is required for a CIA tag is a little bit ridiculous, but that will go away with the #552 branch as that is merged, since it redefines the entire atmosphere.  So I don't want to suggest any solutions for now.

2023-02-01 14:32 UTC, stefanbuehler commented
Overall: Great! This is really nice, the right level of detail. 

My comments:

Just wording: are surrounded by --> are separated by (otherwise wrong meaning)

"O2-CIA-O2-0,O2-CIA-O2-1,O2-CIA-O2-2,O2-CIA-O2-3,O2-CIA-O2-4,O2-CIA-O2-5,O2-CIA-O2-6,O2-CIA-O2-7": Isn't this rather cumbersome? Especially since most users can not know what the band indices mean exactly. How about introducing "O2-CIA-O2" to mean all bands, consistent with how the LBL species work?

Finally, quite a large part of the control file is the RT calculation. In case this is repeated in several of the examples, perhaps kick it out here? Perhaps instead just calculate absorption?

2023-02-02 07:46 UTC, olemke requested changes
Just some typo and style corrections.

2023-02-02 07:46 UTC, olemke commented on examples/arts-cat-data/cia/cia.py
> +Note that this example presumes that you have set ARTS_DATA_PATH to contain
Add "you have set _the environment variable_ ARTS_DATA_PATH" for clarity

2023-02-02 07:46 UTC, olemke commented on examples/arts-cat-data/cia/cia.py
> +band.  To include all CIA band by O2, you have to write:
all CIA band -> all CIA bands

2023-02-02 07:46 UTC, olemke commented on examples/arts-cat-data/cia/cia.py
> +CIA is not just self-induced but can occur between two different moleules.  In
moleules -> molecules

2023-02-02 07:46 UTC, olemke commented on examples/arts-cat-data/cia/cia.py
> +you must ensure that there also exist another N2 species in your ws.abs_species
exist -> exists

2023-02-02 07:46 UTC, olemke commented on examples/arts-cat-data/cia/cia.py
> +ws.iy_unit="PlanckBT"
Minor style issue: missing spaces around the `=` sing

2023-02-02 07:46 UTC, olemke commented on examples/arts-cat-data/cia/cia.py
> +# test that we are still
sentence cut off

2023-02-02 08:44 UTC, riclarsson reviewed
Fix textual stuff from Oliver

2023-02-02 08:45 UTC, riclarsson reviewed
Fix text comment by Stefan

2023-02-02 08:51 UTC, riclarsson commented
@stefanbuehler I will leave introducing "O2-CIA-O2" as a separate branch but also leave this PR open until that issue is resolved.  I agree, there is no point in having "O2-CIA-O2-N", as this just confuses things.  If you want less that or just a specific band, you prepare the data yourself.

Also, I think showing just the absorption is a good idea.  I will change this after checking with Patrick and Oliver at tomorrow's Zoom.

2023-02-08 14:46 UTC, olemke approved these changes

2023-02-08 17:07 UTC, merged